Refactor the windows side too
vmitchell85/luxafor-python pull request #11
Opened 2017-10-09 07:03 UTC by po1

This builds on top of #10 and adds support for windows behind a common user interface.

Though the code should be the same, as I don't have a windows machine I have not been able to test it. @vmitchell85 is this something you can help with?

#### merge order

- [ ] #10
- this PR

2017-10-09 07:03 UTC, po1 commented
@spmaniato FYI

2017-10-10 02:25 UTC, spmaniato requested changes
LGTM @po1 :+1: Just a minor fix in the README (see inline)

2017-10-10 02:25 UTC, spmaniato commented on readme.md
> +    luxafor-linux.py fade -l 255 00ff00
These should be `lux.py` @po1

2017-10-14 18:04 UTC, spmaniato approved these changes

2018-09-07 22:12 UTC, closed without merging